version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: flask_rest_api/flask_live_app:1.0.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@flask_db:5432/postgres_db
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
